spring.application.name=QueueManagment


spring.datasource.url=jdbc:mysql://localhost:3306/queuemanagment
spring.datasource.username=root
spring.datasource.password=suhail
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=fkja;riu940834irjkejfireui4rukfhkureiuejfijdfoiuerdhfdfdkfpe

spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health